// import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import "antd/dist/reset.css";
import "./styles/main.css";
import "./styles/responsive.css";
import { Provider } from "react-redux";
import { store } from "../store";
import ProviderComponents from "../components/ProviderComponents/ProviderComponents";
import AuthLayout from "../components/AuthLayout/AuthLayout";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "MedGap - Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50 to-teal-100 relative  6`}
        // className={`min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50 to-teal-100 relative  ${geistSans.variable} ${geistMono.variable}`}
      >
        <AuthLayout>
       <ProviderComponents>
        {children}
       </ProviderComponents>
       </AuthLayout>
      </body>
    </html>
  );
}
